### ISSUE TITLE
Exception thrown:  A connection with the server could not be established - WebSocketModule

### ISSUE THREAD

**Issue by kcfgl** [ReactWindows/react-native-windows#701]
I've hit an error that seems to have come out of nowhere. Right after the initial load of the JS bundle, the app throws an error.  Earlier today I had added a new reference to a project, but I removed it, cleaned the app, and should be back where I started.  I've restarted the system, RN, VS, and unplugged and plugged everything back in. This occurs on both a physical device and local machine. I'm at a loss.  Any thoughts? Thanks.

```
Exception thrown: 'System.Runtime.InteropServices.COMException' in mscorlib.ni.dll
WinRT information: A connection with the server could not be established
Additional information: The text associated with this error code could not be found.
A connection with the server could not be established

The thread 0x29f4 has exited with code 0 (0x0).
The thread 0x11f8 has exited with code 0 (0x0).
The thread 0x1cc4 has exited with code 0 (0x0).
Exception thrown: 'System.Runtime.InteropServices.COMException' in mscorlib.ni.dll
```
This is not a JS error, it crashes the app.

Attached is a snip of the debug at the breakpoint of the exception.
![errorwebsocket](https://cloud.githubusercontent.com/assets/19731815/18533217/56a0b208-7aaf-11e6-838f-0473dac13cac.PNG)

**Update**: I removed /windows reran react-native windows. Everything built correctly. But I'm still having connection issues. Even the UIExplorer example is having development server errors (NotFound) in this case. A totally clean, brand new app, works and shows the standard RN splash page. I must've inadvertently messed something up, some where ...

**Comment by kcfgl** [comment]
Update: I removed /windows reran react-native windows. Everything built correctly. But I'm still having connection issues. Very weird, because the UIExplorer builds and connects with no issue.  I must've inadvertently messed something up, some where ...

**Comment by kcfgl** [comment]
```
$exception	{"The text associated with this error code could not be found.\r\n\r\nA connection with the server could not be established\r\n"}	System.Runtime.InteropServices.COMException
		StackTrace	"   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()\r\n   at ReactNative.Modules.WebSocket.WebSocketModule.<InitializeInBackground>d__8.MoveNext()"	string

		url	"ws://localhost:8097/devtools"	string

```

**Comment by joewood** [comment]
I'm seeing this too, slightly different error but see it once per second or so continuously:
```
Exception thrown: 'System.Runtime.InteropServices.COMException' in mscorlib.ni.dll
WinRT information: A connection with the server could not be established
```

**Comment by joewood** [comment]
Bit more digging, my error is that app trying to connect to devtools. Remote debugging is switched off - so it shouldn't be attempting it.

**Comment by rozele** [comment]
@joewood The remote debugging is separate from the attempted connection to dev tools, the PR I merged above should take care of this for now, it should be available in 0.34

**Comment by joewood** [comment]
Great, thanks.

**Comment by joewood** [comment]
I've just upgraded to 0.34 and still see this error reported every couple of seconds. Did the fix make it into this release?

**Comment by joewood** [comment]
Correction - a flush of the packager cache fixed it. Looks good now.

**Comment by fatfatson** [comment]
still show this error when trying to connect to a websocket server by socket.io
